server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: buildpcchecker
  datasource:
    # Vẫn giữ localhost vì code Spring Boot và MySQL đang nằm chung trên 1 chiếc VPS
    url: jdbc:mysql://localhost:3306/identity_service
    username: identity_user  # <-- SỬA: Dùng đúng tên user bạn vừa gõ lệnh tạo trên Linux
    password: 123456         # <-- SỬA: Mật khẩu của user đó
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: lookatwidget@gmail.com
    password: yygjtzpdjueh msmr # Nhớ thu hồi sau khi test xong nhé!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

app:
  # <-- SỬA: Thay <IP_VPS_CUA_BAN> bằng địa chỉ IP Public thật (ví dụ: 20.123.45.67)
  base-url: http://20.194.26.75:8080/identity
  file:
    upload-dir: ${user.dir}/uploads/images
  openapi:
    # <-- SỬA: Thay localhost bằng IP VPS để Swagger UI gọi đúng API trên Internet
    dev-url: http://20.194.26.75:8080

jwt:
  signerKey: "ef251fc07ebf85497bf3b3e3c558386a22756bacb907d9e08d345bfe269ede05"
  valid-duration: 300 # in seconds
  refreshable-duration: 1200 # seconds

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
    display-request-duration: true
  show-actuator: false